# Generated by Django 4.2.4 on 2023-08-20 08:56

import auction_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_bidding_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='photo',
            field=models.ImageField(upload_to=auction_app.models.user_directory_path),
        ),
    ]
